mod classify;
mod denominator;
mod digits;
mod gates;
mod orchestrate;
mod parsers;
mod ports;
mod registry;
mod report;
mod requirement;
mod spec;
mod verdict;

pub use gates::{GateAssetError, GatesRoot};
pub use orchestrate::{run_all, run_gate};
pub use ports::{ProcessOutput, ProcessRunner, ToolProbe};
pub use registry::GATES;
pub use report::Report;
pub use requirement::{ProbeTool, Requirement};
pub use spec::{GateCommand, GateSpec};
pub use verdict::{FailReason, GateResult, Verdict};
