#!/usr/bin/env bash
# End-to-end project setup: collects API keys into .env, installs/builds every backend, and kicks
# off the macOS/Xcode update this host needs for iOS. Re-runnable — existing .env values are kept
# unless you type a replacement.
#
# Run from anywhere: `npm run setup` (repo root) or `bash scripts/setup.sh` directly.

set -euo pipefail
cd "$(dirname "$0")/.."   # repo root, regardless of where this was invoked from
ENV_FILE=".env"

echo "== ADHD Focus Orb — end-to-end setup =="
echo "Repo: $(pwd)"
echo

# ── Load any existing .env so re-running this script doesn't blank out keys you already entered ──
EXISTING_GEMINI_API_KEY="${GEMINI_API_KEY:-}"
EXISTING_ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
EXISTING_SARVAM_API_KEY="${SARVAM_API_KEY:-}"
EXISTING_DEEPGRAM_API_KEY="${DEEPGRAM_API_KEY:-}"
EXISTING_FISH_API_KEY="${FISH_API_KEY:-}"
EXISTING_CARTESIA_API_KEY="${CARTESIA_API_KEY:-}"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  . "./$ENV_FILE"
  set +a
  EXISTING_GEMINI_API_KEY="${GEMINI_API_KEY:-$EXISTING_GEMINI_API_KEY}"
  EXISTING_ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-$EXISTING_ANTHROPIC_API_KEY}"
  EXISTING_SARVAM_API_KEY="${SARVAM_API_KEY:-$EXISTING_SARVAM_API_KEY}"
  EXISTING_DEEPGRAM_API_KEY="${DEEPGRAM_API_KEY:-$EXISTING_DEEPGRAM_API_KEY}"
  EXISTING_FISH_API_KEY="${FISH_API_KEY:-$EXISTING_FISH_API_KEY}"
  EXISTING_CARTESIA_API_KEY="${CARTESIA_API_KEY:-$EXISTING_CARTESIA_API_KEY}"
fi

mask() {
  # Show the last 4 characters only, so a re-run doesn't echo the full secret back.
  local v="$1"
  if [ -z "$v" ]; then echo "(not set)"; return; fi
  local len=${#v}
  if [ "$len" -le 4 ]; then echo "****"; return; fi
  echo "****${v: -4}"
}

prompt_secret() {
  # IMPORTANT: this is called as `X="$(prompt_secret ...)"` — command substitution captures
  # EVERYTHING this function writes to stdout. The prompt text itself must go to stderr (>&2), or
  # it gets swallowed into the returned value instead of the actual typed input.
  local label="$1" existing="$2" value
  if [ -n "$existing" ]; then
    printf '%s [currently %s — Enter to keep, or paste a new key]: ' "$label" "$(mask "$existing")" >&2
  else
    printf '%s [optional — Enter to skip]: ' "$label" >&2
  fi
  read -r -s value
  echo >&2
  if [ -z "$value" ]; then
    printf '%s\n' "$existing"
  else
    printf '%s\n' "$value"
  fi
}

echo "-- API keys --"
echo "Every key below is optional except at least one LLM key is recommended (otherwise the"
echo "atomizer runs in deterministic fake/fallback mode only). Paste a key or press Enter to skip."
echo

echo "LLM (pick one; Gemini and Anthropic can both be set, Gemini is preferred if both present):"
GEMINI_API_KEY="$(prompt_secret 'Gemini API key       (aistudio.google.com/apikey)' "$EXISTING_GEMINI_API_KEY")"
ANTHROPIC_API_KEY="$(prompt_secret 'Anthropic API key    (console.anthropic.com)   ' "$EXISTING_ANTHROPIC_API_KEY")"
echo

echo "Speech-to-text (Fish Audio preferred when its key is present; Sarvam/Deepgram otherwise):"
SARVAM_API_KEY="$(prompt_secret 'Sarvam API key       (dashboard.sarvam.ai)     ' "$EXISTING_SARVAM_API_KEY")"
DEEPGRAM_API_KEY="$(prompt_secret 'Deepgram API key     (console.deepgram.com)    ' "$EXISTING_DEEPGRAM_API_KEY")"
echo

echo "Text-to-speech (pick one; Fish preferred if multiple present):"
FISH_API_KEY="$(prompt_secret 'Fish Audio API key   (fish.audio)              ' "$EXISTING_FISH_API_KEY")"
CARTESIA_API_KEY="$(prompt_secret 'Cartesia API key     (cartesia.ai)             ' "$EXISTING_CARTESIA_API_KEY")"
echo

# ── Derive provider-selector env vars from which keys are actually present ──
if [ -n "$GEMINI_API_KEY" ]; then
  ORB_LLM_GATEWAY_ADAPTER=gemini
elif [ -n "$ANTHROPIC_API_KEY" ]; then
  ORB_LLM_GATEWAY_ADAPTER=anthropic
else
  ORB_LLM_GATEWAY_ADAPTER=memory
fi

if [ -n "$FISH_API_KEY" ]; then
  ORB_STT_PROVIDER=fish
elif [ -n "$SARVAM_API_KEY" ]; then
  ORB_STT_PROVIDER=sarvam
elif [ -n "$DEEPGRAM_API_KEY" ]; then
  ORB_STT_PROVIDER=deepgram
else
  ORB_STT_PROVIDER=fake
fi

if [ -n "$FISH_API_KEY" ]; then
  ORB_TTS_PROVIDER=fish
elif [ -n "$SARVAM_API_KEY" ]; then
  ORB_TTS_PROVIDER=sarvam
elif [ -n "$CARTESIA_API_KEY" ]; then
  ORB_TTS_PROVIDER=cartesia
else
  ORB_TTS_PROVIDER=fake
fi

# Always point the Rust relay at our own voice-provider-sidecar (it internally handles the
# fake/real STT+TTS split via ORB_STT_PROVIDER/ORB_TTS_PROVIDER above) rather than relay-rs's
# separate built-in fake — one fewer mode to reason about.
ORB_RELAY_PROVIDER=http
ORB_RELAY_PROVIDER_URL="http://127.0.0.1:\${VOICE_PROVIDER_SIDECAR_PORT:-8083}"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh on $(date +%Y-%m-%d 2>/dev/null || echo unknown-date).
# Loaded by the npm run start:* scripts via scripts/load-env.sh. Never commit this file.

GEMINI_API_KEY="$GEMINI_API_KEY"
ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
SARVAM_API_KEY="$SARVAM_API_KEY"
DEEPGRAM_API_KEY="$DEEPGRAM_API_KEY"
FISH_API_KEY="$FISH_API_KEY"
CARTESIA_API_KEY="$CARTESIA_API_KEY"

ORB_LLM_GATEWAY_ADAPTER="$ORB_LLM_GATEWAY_ADAPTER"
ORB_STT_PROVIDER="$ORB_STT_PROVIDER"
ORB_TTS_PROVIDER="$ORB_TTS_PROVIDER"
ORB_RELAY_PROVIDER="$ORB_RELAY_PROVIDER"
ORB_RELAY_PROVIDER_URL="$ORB_RELAY_PROVIDER_URL"
EOF
echo "Wrote $ENV_FILE (gitignored) — adapter=$ORB_LLM_GATEWAY_ADAPTER stt=$ORB_STT_PROVIDER tts=$ORB_TTS_PROVIDER"
echo

# ── Install / build every workspace ──
echo "-- Installing JS/TS dependencies (npm workspaces + react-native-skia peer conflict needs --legacy-peer-deps) --"
npm install --legacy-peer-deps

echo
echo "-- Python relay venv --"
if [ ! -d backend/relay-py/.venv ]; then
  python3 -m venv backend/relay-py/.venv
fi
backend/relay-py/.venv/bin/pip install --quiet --upgrade pip
backend/relay-py/.venv/bin/pip install --quiet -e "backend/relay-py[dev]"

echo
echo "-- Rust relay build (warms the cargo cache; needs ~/.cargo/bin on PATH) --"
if command -v cargo >/dev/null 2>&1 || [ -x "$HOME/.cargo/bin/cargo" ]; then
  ( cd backend/relay-rs && PATH="$HOME/.cargo/bin:$PATH" cargo build --quiet )
else
  echo "cargo not found — install Rust (https://rustup.rs) before running the relay. Skipping build."
fi

echo
echo "-- Full verify gate --"
PATH="$HOME/.cargo/bin:/opt/homebrew/bin:/usr/local/bin:$PATH" npm run verify

# ── Xcode / CoreSimulator update (asks for your password — that's macOS's own prompt, not this script's) ──
echo
echo "-- iOS toolchain --"
echo "This host's CoreSimulator has been behind Xcode's required version. Two commands can fix"
echo "that; both may prompt for your password/confirmation natively — that's expected."
read -r -p "Run the Xcode iOS platform download + macOS software update now? [y/N] " run_ios
if [ "$run_ios" = "y" ] || [ "$run_ios" = "Y" ]; then
  echo "Downloading the iOS platform via Xcode (may prompt for Apple ID / license acceptance)..."
  xcodebuild -downloadPlatform iOS || echo "xcodebuild download step reported an error — see output above, continue manually if needed."
  echo
  echo "Checking for a macOS update (this can be large and slow; you will be prompted for your"
  echo "password by sudo, and macOS may ask you to confirm the install)..."
  sudo softwareupdate --install --all || echo "softwareupdate reported an error or found nothing to install — see output above."
  echo
  echo "If an OS update installed, restart this Mac, then re-run: npm run native:preflight"
else
  echo "Skipped. Run it later with:"
  echo "  xcodebuild -downloadPlatform iOS && sudo softwareupdate --install --all"
fi

echo
echo "== Setup complete =="
echo "Start the four backend processes (each in its own terminal, or backgrounded):"
echo "  npm run start:sidecar:t0        # LLM gateway  (:8082, adapter=$ORB_LLM_GATEWAY_ADAPTER)"
echo "  npm run start:voice-sidecar:t0  # STT/TTS       (:8083, stt=$ORB_STT_PROVIDER tts=$ORB_TTS_PROVIDER)"
echo "  npm run start:relay:t0          # orchestration (:8765)"
echo "  npm run start:relay:rs:t0       # realtime relay (:8091)"
echo "Then build + run the app: npm run android:build:check (Android) or npm run ios:build:check (iOS, after the toolchain step above completes)."
