//! F06: the contract suite for the `lld-ready` gate (lane contract §7). Written before
//! `fleet::lld_ready` exists and expected to be red until the gate is built (T1/T2 -- see the
//! lane contract's header). Conventions match `f02_lld_crosslang.rs`: fixtures loaded via
//! `CARGO_MANIFEST_DIR`-relative paths, one file, `f{feature}_t{n}_{description}` test names.
//!
//! Per the lane contract's own instruction to this suite's builder: do not edit this file beyond
//! *adding* cases. Any diff that changes or removes an assertion below is a contract breach.

use fleet::lld;
use fleet::lld_ready::{self, EntryOutcome, GateRefs, Outcome};
use serde_json::{json, Value};
use std::fs;
use std::path::PathBuf;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/fixtures/lld"
    ))
}

fn load(name: &str) -> Value {
    let text =
        fs::read_to_string(fixtures_dir().join(format!("{name}.json"))).expect("read fixture");
    serde_json::from_str(&text).expect("fixture must be valid JSON")
}

/// `v["module_brief"]` if `v` is an `lld.v1` wrapper (has a `module_brief` key), else `v` itself.
/// Two of the six fixtures (`complete_freeze.json`, `forged_freeze.json`) are wrappers; the other
/// four are bare `ModuleBrief` objects. `evaluate` only ever sees a bare brief (§5.1).
fn brief_of(v: &Value) -> Value {
    match v.as_object() {
        Some(obj) if obj.contains_key("module_brief") => {
            obj.get("module_brief").cloned().unwrap_or(Value::Null)
        }
        _ => v.clone(),
    }
}

/// Read by the TEST, not the gate (§3.5 -- the gate never reads its own reference data).
fn refs() -> GateRefs {
    let owners_text = fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/owners.v1.json"
    ))
    .expect("read owners.v1.json");
    let owners_json: Value = serde_json::from_str(&owners_text).expect("parse owners.v1.json");
    let owners: Vec<String> = owners_json["owners"]
        .as_array()
        .expect("owners array")
        .iter()
        .map(|v| v.as_str().expect("owner is a string").to_string())
        .collect();

    let refs_text = fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/gate-refs.v1.json"
    ))
    .expect("read gate-refs.v1.json");
    let refs_json: Value = serde_json::from_str(&refs_text).expect("parse gate-refs.v1.json");
    let registry_paths: Vec<String> = refs_json["registry_paths"]
        .as_array()
        .expect("registry_paths array")
        .iter()
        .map(|v| v.as_str().expect("registry path is a string").to_string())
        .collect();
    let known_node_ids: Vec<String> = refs_json["known_node_ids"]
        .as_array()
        .expect("known_node_ids array")
        .iter()
        .map(|v| v.as_str().expect("known node id is a string").to_string())
        .collect();

    GateRefs {
        owners,
        registry_paths,
        known_node_ids,
    }
}

#[test]
fn f06_t1_refuses_the_one_line_freeze_naming_at_least_five_check_ids() {
    let v = lld_ready::evaluate(&load("one_line_freeze"), &refs());
    assert_eq!(v.outcome, Outcome::NotReady);
    let mut ids: Vec<&str> = v.reasons.iter().map(|r| r.check_id).collect();
    ids.sort();
    ids.dedup();
    assert!(
        ids.len() >= 5,
        "expected >=5 distinct failed check ids, got {ids:?}"
    );
    for required in ["C1-OPEN", "C2-OWNER", "R21-ALTS", "R21-FAIL", "SHAPE"] {
        assert!(
            ids.contains(&required),
            "{required} must be among the failed checks, got {ids:?}"
        );
    }
}

#[test]
fn f06_t2_accepts_the_control_fixture_with_checked_driven_to_full_count() {
    let v = lld_ready::evaluate(&load("complete_module"), &refs());
    assert_eq!(v.outcome, Outcome::Ready);
    assert_eq!(v.checked, lld_ready::GATE_CHECK_IDS.len());
    let score = v.score.expect("Ready verdict must carry a score");
    assert_eq!(score.checks_total, 14);
    assert_eq!(score.checks_passed, 14);
    assert_eq!(score.ratio, 1.0);
    assert!(score.failed_check_ids.is_empty());
}

/// A CENSUS, not a sample (§7.5 -- the TS test of the same name is a sample and must not be
/// copied as-is: it covers 8 of 14 ids, asserts `.toContain` rather than equality, and its
/// denominator is the sample's own size). Every mutation below was hand-verified against
/// `complete_module.json`'s actual field values to trip EXACTLY its own check -- several of the
/// TS test's own 8 mutations do not have this property under an exact-equality assertion (e.g.
/// its R19-ABSOLUTE-shaped guarantees replacement also breaks R17-DERIV's calc check on the
/// dropped second guarantee; its C3-ACC-NONTAUT rewrite of `then` also breaks C3-ACC-GROUND by
/// deleting the artifact substring). Each case here was independently constructed to avoid that.
#[test]
fn f06_t3_every_check_id_can_be_failed_in_isolation_from_the_control_fixture() {
    let base = load("complete_module");
    let r = refs();

    type Mutator = fn(&Value) -> Value;
    let cases: [(&str, Mutator); 14] = [
        ("C1-OPEN", |b| {
            let mut b = b.clone();
            b["open_questions"] = json!(["what store?"]);
            b
        }),
        ("C2-OWNER", |b| {
            let mut b = b.clone();
            b["owner"] = json!("me");
            b
        }),
        // oracle_kind is read ONLY by C3-ACC-PARSE -- given/when/then/artifact are untouched, so
        // C3-ACC-GROUND and C3-ACC-NONTAUT cannot be affected.
        ("C3-ACC-PARSE", |b| {
            let mut b = b.clone();
            b["acceptance"]["oracle_kind"] = json!("manual");
            b
        }),
        // artifact no longer starts with owner_path -- `then` (still containing the OLD artifact
        // string) and oracle_kind/given/when are untouched, so C3-ACC-PARSE/C3-ACC-NONTAUT hold.
        ("C3-ACC-GROUND", |b| {
            let mut b = b.clone();
            b["acceptance"]["artifact"] = json!("elsewhere/not-under-owner-path.ts");
            b
        }),
        // Prepending a tautology-pattern-3 prefix ("it should work", which has no trailing
        // anchor in the TS regex -- see lane contract §11.1) trips C3-ACC-NONTAUT while the
        // ORIGINAL artifact substring survives inside `then`, so C3-ACC-GROUND still holds.
        ("C3-ACC-NONTAUT", |b| {
            let mut b = b.clone();
            let original_then = b["acceptance"]["then"]
                .as_str()
                .expect("then is a string")
                .to_string();
            b["acceptance"]["then"] = json!(format!("it should work -- {original_then}"));
            b
        }),
        // Only guarantees[1] (the NUMBER-kind guarantee) is touched; guarantees[0] (the
        // structural, "never"-claiming one that R19-ABSOLUTE depends on) is untouched.
        ("R17-DERIV", |b| {
            let mut b = b.clone();
            b["guarantees"][1]["derivation"]["calc"] = json!("");
            b
        }),
        // A single guarantee whose numeric derivation ("0 = 0") is well-formed, so R17-DERIV
        // still holds; only the absolute claim ("zero") paired with label "mitigates" (not
        // kills_structural) trips R19-ABSOLUTE.
        ("R19-ABSOLUTE", |b| {
            let mut b = b.clone();
            b["guarantees"] = json!([{
                "claim": "zero data loss",
                "label": "mitigates",
                "derivation": { "kind": "number", "value": "0", "calc": "0 = 0" }
            }]);
            b
        }),
        // grain is set to "leaf" alongside the truncation -- not because a correct
        // implementation cares (the flat floor reads no check function's `grain` at all, and no
        // other check reads this field either, so this is a no-op under correct code), but
        // because this is the exact shape (grain='leaf', 1 alternative) that catches mandatory
        // mutation M3 (§7.4 -- reopening the grain='leaf' floor exemption F02 closed). Without
        // it, M3 would only be caught by F06-T10, not this census.
        ("R21-ALTS", |b| {
            let mut b = b.clone();
            b["grain"] = json!("leaf");
            let alts = b["alternatives"]
                .as_array()
                .expect("alternatives array")
                .clone();
            b["alternatives"] = json!([alts[0].clone()]);
            b
        }),
        ("R21-FAIL", |b| {
            let mut b = b.clone();
            b["failure_story"]["blast_radius"] = json!("");
            b
        }),
        // data_owned only, deps untouched -- the new store id ("x") does not collide with
        // "orb-freeze-ledger", so C12-DEPS still holds.
        ("C12-STORE", |b| {
            let mut b = b.clone();
            b["data_owned"] = json!([{"store": "x", "owned_by_node": "someone-else"}]);
            b
        }),
        // A self-dependency. data_owned (empty) is untouched, so C12-STORE still holds.
        ("C12-DEPS", |b| {
            let mut b = b.clone();
            let node_id = b["node_id"]
                .as_str()
                .expect("node_id is a string")
                .to_string();
            b["deps"] = json!([node_id]);
            b
        }),
        ("REG-VERDICT", |b| {
            let mut b = b.clone();
            b["registry"] = json!({"kind": "install", "matched_path": "registry/not-a-real-path"});
            b
        }),
        ("IFACE", |b| {
            let mut b = b.clone();
            b["interface"] = json!([]);
            b
        }),
        // purpose only -- NOT owner_path (cascades into C12-STORE via node ownership prose) or
        // node_id (cascades into C3-ACC-GROUND via owner_path... no: node_id, not owner_path --
        // regardless, purpose is the one field SHAPE alone depends on that nothing else reads).
        ("SHAPE", |b| {
            let mut b = b.clone();
            b["purpose"] = json!("");
            b
        }),
    ];

    assert_eq!(
        cases.len(),
        lld_ready::GATE_CHECK_IDS.len(),
        "the census's loop bound must equal the real check vocabulary, not a sample size"
    );
    let mut case_ids: Vec<&str> = cases.iter().map(|(id, _)| *id).collect();
    case_ids.sort();
    let mut vocabulary: Vec<&str> = lld_ready::GATE_CHECK_IDS.to_vec();
    vocabulary.sort();
    assert_eq!(
        case_ids, vocabulary,
        "case ids must be exactly the check vocabulary -- a 15th id with no case must fail this, \
         not silently under-count"
    );

    for (id, mutate) in cases {
        let mutated = mutate(&base);
        let verdict = lld_ready::evaluate(&mutated, &r);
        assert_eq!(verdict.outcome, Outcome::NotReady, "case {id}");
        let failed: Vec<&str> = verdict
            .reasons
            .iter()
            .map(|reason| reason.check_id)
            .collect();
        assert_eq!(
            failed,
            vec![id],
            "case {id} must trip EXACTLY its own check and no other, got {failed:?}"
        );
    }
}

#[test]
fn f06_t4_a_thirteen_of_fourteen_brief_is_not_ready_the_ratio_is_never_a_threshold() {
    let mut brief = load("complete_module");
    brief["open_questions"] = json!(["one"]);
    let v = lld_ready::evaluate(&brief, &refs());
    assert_eq!(v.outcome, Outcome::NotReady);
    let score = v.score.expect("NotReady still carries a score");
    assert!(
        (score.ratio - 0.929).abs() < 1e-9,
        "expected ratio ~0.929 (13/14 rounded), got {}",
        score.ratio
    );
    assert!(score.ratio > 0.9, "a near-perfect ratio is still a refusal");
}

#[test]
fn f06_t5_the_gate_is_pure_no_io_no_clock_no_randomness() {
    let src = fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/src/lld_ready.rs")).unwrap();
    for pattern in [
        "std::fs",
        "File::",
        "std::net",
        "SystemTime",
        "Instant",
        "rand",
        "reqwest",
        "tokio",
        "env::",
        "include_str!",
    ] {
        assert!(
            !src.contains(pattern),
            "lld_ready.rs must not reference {pattern} (03 §2.1: 0 io, 0 clock, 0 randomness)"
        );
    }

    let brief = load("complete_module");
    let r = refs();
    let first = lld_ready::evaluate(&brief, &r);
    for _ in 0..100 {
        assert_eq!(lld_ready::evaluate(&brief, &r), first);
    }

    // Order-invariance: this crate's serde_json::Value has no `preserve_order` feature (lld.rs's
    // own comment), so its Object variant is a BTreeMap and already order-normalizes every
    // object regardless of the source JSON's textual key order -- reparsing the same fixture
    // with shuffled top-level keys cannot exercise anything `evaluate` could get wrong. The
    // property that COULD be wrong is array element order (e.g. a check that only looked at
    // guarantees[0]), so this reverses every array field's element order instead and asserts an
    // identical verdict -- the F02 `lld-v1.test.ts` shuffle property, adapted to what this
    // crate's Value representation can actually vary.
    let mut reordered = brief.clone();
    if let Some(obj) = reordered.as_object_mut() {
        for key in [
            "guarantees",
            "alternatives",
            "interface",
            "data_owned",
            "deps",
            "non_goals",
            "open_questions",
        ] {
            if let Some(Value::Array(items)) = obj.get_mut(key) {
                items.reverse();
            }
        }
    }
    assert_eq!(lld_ready::evaluate(&reordered, &r), first);
}

#[test]
fn f06_t6_an_empty_check_set_is_measured_nothing_never_ready() {
    let brief = load("complete_module");
    let r = refs();

    let empty = lld_ready::evaluate_with(&brief, &r, &[]);
    assert_eq!(empty.outcome, Outcome::MeasuredNothing);
    assert_eq!(empty.checked, 0);
    assert!(
        empty.score.is_none(),
        "a zero denominator must carry no score"
    );
    assert!(empty.reasons.is_empty());

    // Not a bad fixture wearing a MeasuredNothing costume: the SAME brief is Ready under the
    // real (14-check) evaluator.
    let full = lld_ready::evaluate(&brief, &r);
    assert_eq!(full.outcome, Outcome::Ready);
}

#[test]
fn f06_t7_the_cli_refuses_a_shape_invalid_brief_before_the_gate_runs() {
    let bad = load("one_line_freeze");
    match lld_ready::check_and_evaluate(&bad, &refs()) {
        EntryOutcome::ShapeInvalid(violations) => {
            assert!(
                !violations.is_empty(),
                "shape check must name real violations"
            )
        }
        EntryOutcome::Gate(_) => panic!("a shape-invalid brief must never reach the gate"),
    }

    let good = load("complete_module");
    match lld_ready::check_and_evaluate(&good, &refs()) {
        EntryOutcome::Gate(verdict) => assert_eq!(verdict.outcome, Outcome::Ready),
        EntryOutcome::ShapeInvalid(violations) => {
            panic!("control fixture must pass shape and reach the gate: {violations:?}")
        }
    }
}

#[test]
fn f06_t8_the_emitted_depth_evidence_validates_against_the_merged_freeze_schema() {
    let brief = load("complete_module");
    let r = refs();
    let ready = lld_ready::evaluate(&brief, &r);
    assert_eq!(ready.outcome, Outcome::Ready);
    let evidence = lld_ready::depth_evidence(&ready).expect("a Ready verdict must carry evidence");

    let checked_ids: Vec<&str> = evidence["checked_check_ids"]
        .as_array()
        .expect("checked_check_ids array")
        .iter()
        .map(|v| v.as_str().expect("check id is a string"))
        .collect();
    assert_eq!(
        checked_ids,
        lld_ready::GATE_CHECK_IDS.to_vec(),
        "checked_check_ids must be all 14 ids, in GATE_CHECK_IDS order"
    );
    let failed_ids: Vec<&str> = evidence["score"]["failed_check_ids"]
        .as_array()
        .expect("failed_check_ids array")
        .iter()
        .map(|v| v.as_str().expect("check id is a string"))
        .collect();
    assert!(
        failed_ids.iter().all(|id| checked_ids.contains(id)),
        "failed_check_ids must be a subset of checked_check_ids"
    );

    let mut wrapper = load("complete_freeze");
    wrapper["freeze"]["depth_evidence"] = evidence;
    let violations = lld::validate_lld_v1(&wrapper);
    assert!(
        !violations
            .iter()
            .any(|v| v.path.starts_with("freeze.depth_evidence")),
        "the emitted depth_evidence must validate against freeze.v1: {violations:?}"
    );

    let measured_nothing = lld_ready::evaluate_with(&brief, &r, &[]);
    assert!(lld_ready::depth_evidence(&measured_nothing).is_none());
}

#[test]
fn f06_t9_the_gate_is_the_only_writer_of_the_stamper_literal() {
    let ready_src =
        fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/src/lld_ready.rs")).unwrap();
    assert_eq!(
        ready_src.matches("keel:lld-ready").count(),
        1,
        "exactly one occurrence of the stamp literal in lld_ready.rs"
    );
    let stamp_line = ready_src
        .lines()
        .find(|line| line.contains("keel:lld-ready"))
        .expect("the literal must appear on some line");
    assert!(
        stamp_line.contains("STAMPED_BY"),
        "the one occurrence must be the STAMPED_BY const's own definition, got: {stamp_line:?}"
    );

    // F02's invariant (lld.rs:653-666) must survive this lane's visibility-only edit: still a
    // single COMPARISON, never a second writer.
    let lld_src = fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/src/lld.rs")).unwrap();
    assert_eq!(lld_src.matches("keel:lld-ready").count(), 1);
    let lld_line = lld_src
        .lines()
        .find(|line| line.contains("keel:lld-ready"))
        .expect("the literal must appear on some line");
    assert!(
        lld_line.contains("=="),
        "lld.rs's occurrence must still be a comparison: {lld_line:?}"
    );

    let brief = load("complete_module");
    let r = refs();
    let ready = lld_ready::evaluate(&brief, &r);
    let mut wrapper = load("complete_freeze");
    wrapper["freeze"]["depth_evidence"] =
        lld_ready::depth_evidence(&ready).expect("Ready verdict carries evidence");

    wrapper["freeze"]["stamped_by"] = json!(lld_ready::STAMPED_BY);
    assert!(
        !lld::validate_lld_v1(&wrapper)
            .iter()
            .any(|v| v.path == "freeze.stamped_by"),
        "the gate's own const must be accepted"
    );

    wrapper["freeze"]["stamped_by"] = json!("orb:lld-ready");
    assert!(
        lld::validate_lld_v1(&wrapper)
            .iter()
            .any(|v| v.path == "freeze.stamped_by"),
        "a forged stamp must be refused"
    );
}

/// The Rust half of the cross-language comparator (§7.2). `fleet/tests/acceptance/
/// lld-ready-crosslang.sh` runs this test with `F06_REPORT_OUT` set to a real path and diffs the
/// result against the TS mirror's report (`fleet/tests/acceptance/lld_ready_ts_report.mts`, a
/// small Node script over the same 6 fixtures -- not a new file under orb/, which this lane does
/// not touch). Without the env var this test still runs (discarding to /dev/null), matching
/// `f02_t12_emits_the_cross_language_report`'s exact pattern.
#[test]
fn f06_t10_rust_and_ts_gates_agree_on_every_fixture() {
    // Sorted -- matches the TS report script and lld.rs's own cross_lang_report convention of a
    // sorted fixture-name key order (this crate's serde_json::Map is a BTreeMap and would sort
    // these regardless, but the TS side has no such guarantee and must insert in this same order).
    const FIXTURE_NAMES: [&str; 6] = [
        "complete_freeze",
        "complete_module",
        "forged_freeze",
        "numeric_trap",
        "one_alternative",
        "one_line_freeze",
    ];
    let r = refs();
    let mut fixtures = serde_json::Map::new();
    for name in FIXTURE_NAMES {
        let brief = brief_of(&load(name));
        let verdict = lld_ready::evaluate(&brief, &r);
        let mut failed: Vec<String> = verdict
            .reasons
            .iter()
            .map(|reason| reason.check_id.to_string())
            .collect();
        failed.sort();
        let outcome_str = match verdict.outcome {
            Outcome::Ready => "READY",
            Outcome::NotReady => "NOT_READY",
            Outcome::MeasuredNothing => "MEASURED_NOTHING",
        };
        let mut entry = serde_json::Map::new();
        entry.insert(
            "failed_check_ids".to_string(),
            Value::Array(failed.into_iter().map(Value::String).collect()),
        );
        entry.insert(
            "outcome".to_string(),
            Value::String(outcome_str.to_string()),
        );
        fixtures.insert(name.to_string(), Value::Object(entry));
    }
    let mut report = serde_json::Map::new();
    report.insert("fixtures".to_string(), Value::Object(fixtures));
    report.insert("gate".to_string(), Value::String("lld-ready".to_string()));
    report.insert("mirror".to_string(), Value::String("rs".to_string()));
    let report = Value::Object(report);

    let out = std::env::var("F06_REPORT_OUT").unwrap_or_else(|_| "/dev/null".to_string());
    fs::write(
        out,
        serde_json::to_string_pretty(&report).expect("report must serialize"),
    )
    .expect("write report");
}
