//! F07: the contract suite for `fleet sow --lld <PATH>` (lane contract §7, `docs/lane-contracts/
//! F07-sow-intake.md`). Cargo INTEGRATION test -- drives the real compiled `fleet` binary via
//! subprocess (see `tests/f08_pr_emit.rs` / `tests/s3_lanes.rs` for why a unit test cannot
//! exercise CLI-level exit codes, stderr framing, and `state/sows/` filesystem side effects).
//!
//! Per the lane contract's own instruction to this suite's builder: do not edit this file beyond
//! *adding* cases. Any diff that changes or removes an assertion below is a contract breach.
//!
//! T6/T7/T8/T9/T14 need wrappers that are not checked-in fixtures. Built here at test runtime by
//! loading an existing lead-specified fixture (`complete_freeze.json`, `numeric_trap.json`,
//! `one_line_freeze.json`) and mutating exactly the field each test's own contract row names --
//! composition inside the test, never fixture editing (lane contract §7.1's explicit permission).
//! Every mutation that touches `module_brief` recomputes `content_hash` with the REAL production
//! function (`rehash`, below) before writing the wrapper to disk, or step 3 (this lane's own hash
//! guard) would refuse it for an unrelated reason before the test's own guard is ever reached.

use fleet::lld;
use serde_json::{json, Value};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn fleet_bin() -> &'static str {
    env!("CARGO_BIN_EXE_fleet")
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/fixtures/lld"
    ))
}

fn load_fixture(name: &str) -> Value {
    let text = fs::read_to_string(fixtures_dir().join(format!("{name}.json")))
        .unwrap_or_else(|error| panic!("read fixture {name}: {error}"));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("parse fixture {name}: {error}"))
}

fn unique_dir(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "fleet-f07-{tag}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir_all(&dir).expect("create fixture dir");
    dir
}

/// Writes `value` as pretty JSON under a fresh unique temp dir tagged `dir_tag` and returns the
/// file's path.
fn write_temp_json(dir_tag: &str, file_name: &str, value: &Value) -> PathBuf {
    let dir = unique_dir(dir_tag);
    let path = dir.join(file_name);
    fs::write(
        &path,
        serde_json::to_vec_pretty(value).expect("serialize temp fixture"),
    )
    .expect("write temp fixture");
    path
}

/// Recomputes `content_hash` over `wrapper["module_brief"]` with the REAL `lld::content_hash`
/// (never a reimplementation) and writes it into `wrapper["freeze"]["content_hash"]`. Call this
/// after any mutation to `module_brief`.
fn rehash(wrapper: &mut Value) {
    let hash = lld::content_hash(&wrapper["module_brief"])
        .expect("test mutation made module_brief unhashable -- fix the mutation, not this helper");
    wrapper["freeze"]["content_hash"] = Value::String(hash);
}

fn run_sow_lld(state: &Path, lld_path: &Path) -> Output {
    Command::new(fleet_bin())
        .arg("sow")
        .arg("--lld")
        .arg(lld_path)
        .env("FLEET_STATE", state)
        .output()
        .expect("run fleet sow --lld")
}

fn run_sow_task(state: &Path, task: &str) -> Output {
    Command::new(fleet_bin())
        .arg("sow")
        .arg("--task")
        .arg(task)
        .env("FLEET_STATE", state)
        .output()
        .expect("run fleet sow --task")
}

fn run_sow_accept(state: &Path, id: &str) -> Output {
    Command::new(fleet_bin())
        .args(["sow", "accept", "--id", id])
        .env("FLEET_STATE", state)
        .output()
        .expect("run fleet sow accept")
}

fn run_contract_lld_validate(path: &Path) -> Output {
    Command::new(fleet_bin())
        .args(["contract", "lld", "validate"])
        .arg(path)
        .output()
        .expect("run fleet contract lld validate")
}

fn run_gate_lld_ready(path: &Path) -> Output {
    Command::new(fleet_bin())
        .args(["gate", "lld-ready"])
        .arg(path)
        .output()
        .expect("run fleet gate lld-ready")
}

fn stdout_of(out: &Output) -> String {
    String::from_utf8_lossy(&out.stdout).into_owned()
}
fn stderr_of(out: &Output) -> String {
    String::from_utf8_lossy(&out.stderr).into_owned()
}

/// Finds a line starting with `prefix` and returns the value of `key=` within it (mirrors
/// `tests/f08_pr_emit.rs`'s identical helper; duplicated locally per this crate's convention of
/// no shared `tests/common` module).
fn field(text: &str, prefix: &str, key: &str) -> Option<String> {
    text.lines()
        .find_map(|line| line.strip_prefix(prefix))?
        .split_whitespace()
        .find_map(|token| token.split_once('=').filter(|(k, _)| *k == key))
        .map(|(_, v)| v.to_string())
}

fn extract_delimited(text: &str, begin: &str, end: &str) -> Option<String> {
    let start = text.find(begin)? + begin.len();
    let rest = &text[start..];
    let stop = rest.find(end)?;
    Some(rest[..stop].trim_matches('\n').to_string())
}

fn sows_in(state: &Path) -> Vec<PathBuf> {
    fs::read_dir(state.join("sows"))
        .map(|entries| {
            entries
                .filter_map(|entry| entry.ok())
                .map(|entry| entry.path())
                .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("json"))
                .collect()
        })
        .unwrap_or_default()
}

fn load_record(state: &Path, id: &str) -> Value {
    let text = fs::read_to_string(state.join("sows").join(format!("{id}.json")))
        .unwrap_or_else(|error| panic!("read record {id}: {error}"));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("parse record {id}: {error}"))
}

fn cleanup(dirs: &[&Path]) {
    for dir in dirs {
        fs::remove_dir_all(dir).ok();
    }
}

fn normalize_ws(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

// ------------------------------------------------------------------------------------- T1 -----

#[test]
fn f07_t1_complete_freeze_reaches_sow_ready_with_at_least_one_leaf_and_two_alternatives() {
    let state = unique_dir("t1-state");
    let out = run_sow_lld(&state, &fixtures_dir().join("complete_freeze.json"));
    let stderr = stderr_of(&out);
    assert_eq!(out.status.code(), Some(9), "stderr:\n{stderr}");

    let id = field(&stderr, "SOW_READY_AWAITING_REVIEW ", "id").expect("id field on stderr");
    assert_eq!(id.len(), 64, "id must be 64 hex chars: {id:?}");
    assert!(
        id.bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase()),
        "id must be lowercase hex: {id:?}"
    );
    assert!(
        state.join("sows").join(format!("{id}.json")).exists(),
        "record not written"
    );

    let record = load_record(&state, &id);
    assert!(
        record["sow"]["leaves"]
            .as_array()
            .map(Vec::len)
            .unwrap_or(0)
            >= 1,
        "record: {record}"
    );
    assert!(
        record["sow"]["alternatives"]
            .as_array()
            .map(Vec::len)
            .unwrap_or(0)
            >= 2,
        "record: {record}"
    );
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------- T2 -----

#[test]
fn f07_t2_identity_round_trip_produces_the_same_id_via_task_not_exit_mismatch() {
    let state = unique_dir("t2-state");
    let out1 = run_sow_lld(&state, &fixtures_dir().join("complete_freeze.json"));
    let stderr1 = stderr_of(&out1);
    assert_eq!(out1.status.code(), Some(9), "stderr:\n{stderr1}");
    let id1 = field(&stderr1, "SOW_READY_AWAITING_REVIEW ", "id").expect("id field");
    let task_text = extract_delimited(&stderr1, "SOW_LLD_TASK_BEGIN", "SOW_LLD_TASK_END")
        .expect("delimited task text on stderr");

    let out2 = run_sow_task(&state, &task_text);
    let stderr2 = stderr_of(&out2);
    assert_ne!(
        out2.status.code(),
        Some(8),
        "round-trip must not be EXIT_MISMATCH; stderr:\n{stderr2}"
    );
    assert_eq!(out2.status.code(), Some(9), "stderr:\n{stderr2}");
    let id2 = field(&stderr2, "SOW_READY_AWAITING_REVIEW ", "id").expect("id field");
    assert_eq!(id1, id2, "the two intakes produced different SOWs");
    assert_eq!(
        sows_in(&state).len(),
        1,
        "expected exactly one record in state/sows/ after the round-trip"
    );
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------- T3 -----

#[test]
fn f07_t3_compiling_the_same_fixture_twice_in_separate_processes_is_byte_identical() {
    let state1 = unique_dir("t3-state-a");
    let state2 = unique_dir("t3-state-b");
    let fixture = fixtures_dir().join("complete_freeze.json");
    let out1 = run_sow_lld(&state1, &fixture);
    let out2 = run_sow_lld(&state2, &fixture);
    let stderr1 = stderr_of(&out1);
    let stderr2 = stderr_of(&out2);
    assert_eq!(out1.status.code(), Some(9), "stderr:\n{stderr1}");
    assert_eq!(out2.status.code(), Some(9), "stderr:\n{stderr2}");

    let text1 = extract_delimited(&stderr1, "SOW_LLD_TASK_BEGIN", "SOW_LLD_TASK_END").unwrap();
    let text2 = extract_delimited(&stderr2, "SOW_LLD_TASK_BEGIN", "SOW_LLD_TASK_END").unwrap();
    assert_eq!(
        text1, text2,
        "compiled task text differs across two separate processes"
    );

    let id1 = field(&stderr1, "SOW_READY_AWAITING_REVIEW ", "id").unwrap();
    let id2 = field(&stderr2, "SOW_READY_AWAITING_REVIEW ", "id").unwrap();
    assert_eq!(id1, id2);
    cleanup(&[&state1, &state2]);
}

// ------------------------------------------------------------------------------------- T4 -----

#[test]
fn f07_t4_forged_hash_is_refused_but_both_existing_commands_still_wrongly_pass_it() {
    let forged = fixtures_dir().join("hash_forged_freeze.json");
    let wrapper = load_fixture("hash_forged_freeze");

    // Controls FIRST: prove the hole this lane closes is real, on THIS exact file, before
    // asserting the fix. This is F07 contract §2.1 made mechanical.
    let validate_out = run_contract_lld_validate(&forged);
    assert_eq!(
        validate_out.status.code(),
        Some(0),
        "control: fleet contract lld validate must still pass the forged file (it only checks \
         the hash's PATTERN, never recomputes it); stdout:\n{}",
        stdout_of(&validate_out)
    );

    let brief_path = write_temp_json("t4-brief", "module_brief.json", &wrapper["module_brief"]);
    let gate_out = run_gate_lld_ready(&brief_path);
    assert_eq!(
        gate_out.status.code(),
        Some(0),
        "control: fleet gate lld-ready on the forged file's own brief must still report READY \
         (module_brief itself is untouched by the forgery); stdout:\n{}",
        stdout_of(&gate_out)
    );

    // Now the real fix: `fleet sow --lld` is the first consumer that recomputes the hash.
    let state = unique_dir("t4-state");
    let out = run_sow_lld(&state, &forged);
    let stdout = stdout_of(&out);
    assert_eq!(
        out.status.code(),
        Some(7),
        "stdout:\n{stdout}\nstderr:\n{}",
        stderr_of(&out)
    );
    assert_eq!(
        field(&stdout, "sow_lld_refused: ", "reason").as_deref(),
        Some("FREEZE_HASH_MISMATCH")
    );
    assert!(sows_in(&state).is_empty(), "a refusal must write no record");
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------- T5 -----

#[test]
fn f07_t5_wrong_stamped_by_is_refused_before_any_record_appears() {
    let state = unique_dir("t5-state");
    let out = run_sow_lld(&state, &fixtures_dir().join("forged_freeze.json"));
    let stderr = stderr_of(&out);
    // Caught at step 2 (shape: `check_freeze` already rejects any `stamped_by` other than the
    // gate's own const) -- EXIT_MISMATCH, same as `fleet contract lld validate` would report,
    // never reaching step 3+. Pinned to the specific code and the specific violation path (not
    // just "non-zero"): a red-on-arrival run against the un-implemented tree showed a bare
    // "non-zero, no record" assertion also passes for the WRONG reason (falling through to the
    // CLI's generic INVALID_SOW_ARGS refusal, exit 7) -- this would not have caught a real
    // regression that made `--lld` silently accept a forged stamp.
    assert_eq!(out.status.code(), Some(8), "stderr:\n{stderr}");
    assert!(
        stderr.contains("freeze.stamped_by"),
        "refusal must name the violated path: {stderr}"
    );
    assert!(sows_in(&state).is_empty());
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------- T6 -----

#[test]
fn f07_t6_numeric_leaf_in_module_brief_is_refused_as_unhashable_never_a_panic() {
    let mut wrapper = load_fixture("complete_freeze");
    let numeric_trap = load_fixture("numeric_trap");
    let grafted_depth_evidence = numeric_trap["depth_evidence"].clone();
    assert!(
        grafted_depth_evidence.is_object(),
        "numeric_trap.json must carry a depth_evidence object to graft"
    );
    // Grafted into `guarantees[1].derivation`, a location `validate_module_brief` never
    // enumerates or type-checks (it only ever reads `kind`/`calc`/`enforced_by` there) -- so
    // shape validation (step 2) still passes and step 3 (this lane's new hash guard) is what
    // must catch the leaf. This is what makes `unwrap()` on `NumericLeafError` an observable
    // failure mode rather than dead code shape validation would have caught first.
    wrapper["module_brief"]["guarantees"][1]["derivation"]["depth_evidence"] =
        grafted_depth_evidence;
    // Do NOT rehash: the whole point of this test is that module_brief can no longer be hashed.
    assert!(
        lld::validate_lld_v1(&wrapper).is_empty(),
        "construction bug: this mutation must remain shape-valid, or this test exercises shape \
         validation (exit 8) instead of the hash guard (exit 7)"
    );

    let path = write_temp_json("t6-wrapper", "wrapper.json", &wrapper);
    let state = unique_dir("t6-state");
    let out = run_sow_lld(&state, &path);
    let stdout = stdout_of(&out);
    assert_eq!(
        out.status.code(),
        Some(7),
        "stdout:\n{stdout}\nstderr:\n{}",
        stderr_of(&out)
    );
    assert_eq!(
        field(&stdout, "sow_lld_refused: ", "reason").as_deref(),
        Some("FREEZE_UNHASHABLE")
    );
    assert!(sows_in(&state).is_empty());
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------- T7 -----

#[test]
fn f07_t7_registry_verdict_install_or_extract_short_circuits_before_any_write() {
    for kind in ["install", "extract"] {
        let mut wrapper = load_fixture("complete_freeze");
        let verdict = json!({"kind": kind, "matched_path": "registry/services/llm-gateway"});
        wrapper["module_brief"]["registry"] = verdict.clone();
        wrapper["sow_seed"]["registry_verdict"] = verdict;
        rehash(&mut wrapper);
        assert!(
            lld::validate_lld_v1(&wrapper).is_empty(),
            "construction bug for kind={kind}"
        );

        let path = write_temp_json(&format!("t7-{kind}"), "wrapper.json", &wrapper);
        let state = unique_dir(&format!("t7-{kind}-state"));
        let out = run_sow_lld(&state, &path);
        let stdout = stdout_of(&out);
        assert_eq!(
            out.status.code(),
            Some(7),
            "kind={kind} stdout:\n{stdout}\nstderr:\n{}",
            stderr_of(&out)
        );
        assert_eq!(
            field(&stdout, "sow_lld_refused: ", "reason").as_deref(),
            Some("REGISTRY_REUSE"),
            "kind={kind}"
        );
        assert_eq!(
            field(&stdout, "sow_lld_refused: ", "matched_path").as_deref(),
            Some("registry/services/llm-gateway"),
            "kind={kind}"
        );
        assert!(sows_in(&state).is_empty(), "kind={kind}");
        cleanup(&[&state]);
    }
}

// ------------------------------------------------------------------------------------- T8 -----

#[test]
fn f07_t8_registry_verdict_split_between_module_brief_and_sow_seed_is_refused() {
    let mut wrapper = load_fixture("complete_freeze");
    // Mutate ONLY sow_seed's copy -- module_brief.registry (and its hash) stay untouched, so the
    // split is entirely within sow_seed, isolating this guard from step 3's hash guard.
    wrapper["sow_seed"]["registry_verdict"] =
        json!({"kind": "install", "matched_path": "registry/services/llm-gateway"});
    assert!(
        lld::validate_lld_v1(&wrapper).is_empty(),
        "construction bug"
    );

    let path = write_temp_json("t8-wrapper", "wrapper.json", &wrapper);
    let state = unique_dir("t8-state");
    let out = run_sow_lld(&state, &path);
    let stdout = stdout_of(&out);
    assert_eq!(
        out.status.code(),
        Some(7),
        "stdout:\n{stdout}\nstderr:\n{}",
        stderr_of(&out)
    );
    assert_eq!(
        field(&stdout, "sow_lld_refused: ", "reason").as_deref(),
        Some("REGISTRY_VERDICT_SPLIT")
    );
    assert!(sows_in(&state).is_empty());
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------- T9 -----

#[test]
fn f07_t9_readiness_gate_is_actually_invoked_not_skipped_on_the_lld_path() {
    let mut wrapper = load_fixture("complete_freeze");
    let one_line_freeze = load_fixture("one_line_freeze");
    let open_question = one_line_freeze["open_questions"][0].clone();
    assert!(
        open_question.is_string(),
        "one_line_freeze.json must carry a real open question to borrow"
    );
    // Shape only requires open_questions to be an array of strings (any content); C1-OPEN
    // requires it EMPTY. This is a defect ONLY the readiness gate catches -- exactly what
    // isolates "the gate ran and refused" from "shape already refused it" (exit 6 vs exit 8).
    wrapper["module_brief"]["open_questions"] = json!([open_question]);
    rehash(&mut wrapper);
    assert!(
        lld::validate_lld_v1(&wrapper).is_empty(),
        "construction bug: must remain shape-valid so the readiness gate is what's exercised"
    );

    let path = write_temp_json("t9-wrapper", "wrapper.json", &wrapper);
    let state = unique_dir("t9-state");
    let out = run_sow_lld(&state, &path);
    let stderr = stderr_of(&out);
    assert_eq!(
        out.status.code(),
        Some(6),
        "stdout:\n{}\nstderr:\n{stderr}",
        stdout_of(&out)
    );
    assert!(
        stderr.contains("C1-OPEN"),
        "per-check reason must name the failed check on stderr:\n{stderr}"
    );
    assert!(sows_in(&state).is_empty());
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------ T10 -----

#[test]
fn f07_t10_the_single_leaf_carries_the_predicate_then_text_verbatim() {
    let wrapper = load_fixture("complete_freeze");
    let then_text = wrapper["sow_seed"]["blind_suite_seed"]["predicate"]["then"]
        .as_str()
        .unwrap()
        .to_string();
    // This fixture keeps freeze.accepts_when and sow_seed.blind_suite_seed's predicates
    // identical, so this also equals freeze.accepts_when.predicate.then (the lane contract's
    // own T10 wording) -- recorded here, not depended on: the compiler's real source, per §6.1's
    // table, is sow_seed.blind_suite_seed.
    assert_eq!(
        then_text,
        wrapper["freeze"]["accepts_when"]["predicate"]["then"]
            .as_str()
            .unwrap()
    );

    let state = unique_dir("t10-state");
    let out = run_sow_lld(&state, &fixtures_dir().join("complete_freeze.json"));
    let stderr = stderr_of(&out);
    assert_eq!(out.status.code(), Some(9), "stderr:\n{stderr}");
    let id = field(&stderr, "SOW_READY_AWAITING_REVIEW ", "id").unwrap();
    let record = load_record(&state, &id);
    let leaves = record["sow"]["leaves"].as_array().expect("leaves array");
    assert_eq!(
        leaves.len(),
        1,
        "exactly one leaf expected from one accepts_when predicate"
    );
    let requirement = leaves[0]["requirement"]
        .as_str()
        .expect("requirement string");
    assert!(
        requirement.contains(&then_text),
        "requirement {requirement:?} does not contain {then_text:?}"
    );
    assert_eq!(
        leaves[0]["acceptance_predicates"].as_array().map(Vec::len),
        Some(1),
        "leaf must carry exactly one predicate: {:?}",
        leaves[0]
    );
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------ T11 -----

#[test]
fn f07_t11_every_killed_alternative_becomes_one_tradeoff_in_order_none_invented_none_dropped() {
    let wrapper = load_fixture("complete_freeze");
    let killed = wrapper["freeze"]["killed_alternatives"]
        .as_array()
        .unwrap()
        .clone();

    let state = unique_dir("t11-state");
    let out = run_sow_lld(&state, &fixtures_dir().join("complete_freeze.json"));
    let stderr = stderr_of(&out);
    assert_eq!(out.status.code(), Some(9), "stderr:\n{stderr}");
    let id = field(&stderr, "SOW_READY_AWAITING_REVIEW ", "id").unwrap();
    let record = load_record(&state, &id);
    let alternatives = record["sow"]["alternatives"]
        .as_array()
        .expect("alternatives array");
    assert_eq!(
        alternatives.len(),
        killed.len(),
        "alternative count must match killed_alternatives exactly (>=2 by schema minItems)"
    );
    assert!(alternatives.len() >= 2);
    for (index, (alternative, kill)) in alternatives.iter().zip(killed.iter()).enumerate() {
        let expected = normalize_ws(kill["revive_trigger"].as_str().unwrap());
        let actual = alternative["tradeoff"].as_str().unwrap_or("");
        assert_eq!(actual, expected, "alternatives[{index}].tradeoff mismatch");
    }
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------ T12 -----

#[test]
fn f07_t12_estimate_is_the_exact_honest_non_estimate_literal_never_a_fabricated_number() {
    const LITERAL: &str =
        "not estimated at freeze time (lld.v1 carries no estimate field; F07 contract §6.4)";

    let state = unique_dir("t12-state");
    let out = run_sow_lld(&state, &fixtures_dir().join("complete_freeze.json"));
    let stderr = stderr_of(&out);
    assert_eq!(out.status.code(), Some(9), "stderr:\n{stderr}");
    let task_text = extract_delimited(&stderr, "SOW_LLD_TASK_BEGIN", "SOW_LLD_TASK_END").unwrap();
    assert!(
        task_text.contains(&format!("- {LITERAL}")),
        "task text:\n{task_text}"
    );

    let id = field(&stderr, "SOW_READY_AWAITING_REVIEW ", "id").unwrap();
    let record = load_record(&state, &id);
    assert_eq!(record["sow"]["ESTIMATE"].as_str(), Some(LITERAL));
    cleanup(&[&state]);
}

// ------------------------------------------------------------------------------------ T13 -----

#[test]
fn f07_t13_task_path_is_undisturbed_and_an_lld_record_can_be_accepted() {
    // (a) --task path unaffected: same record shape sow.rs's own tests already exercise, and no
    // lld_provenance key (that field belongs only to the --lld origin).
    let state_task = unique_dir("t13-task-state");
    let good_task = "Task: wire crew.sow into Fleet.\n\
Leaves:\n\
- invoke crew.sow | acceptance: requirement_present(1)\n\
Challenges:\n\
- bridge drift [crew/crew/sow.py:1]\n\
Alternatives:\n\
- Bridge: invoke Python | tradeoff: Python is required\n\
- Port: rewrite in Rust | tradeoff: validation can drift\n\
Estimate:\n\
- 1 engineer-day\n\
Edge cases:\n\
- Python is unavailable";
    let out1 = run_sow_task(&state_task, good_task);
    let stderr1 = stderr_of(&out1);
    assert_eq!(out1.status.code(), Some(9), "stderr:\n{stderr1}");
    let id1 = field(&stderr1, "SOW_READY_AWAITING_REVIEW ", "id").unwrap();
    let record1 = load_record(&state_task, &id1);
    assert!(
        record1.get("lld_provenance").is_none(),
        "a --task record must never carry lld_provenance: {record1}"
    );
    assert!(record1["accepted"].is_null());
    assert_eq!(record1["id"].as_str(), Some(id1.as_str()));
    assert_eq!(record1["task"].as_str(), Some(good_task));

    // (b) a --lld record can be accepted, and satisfies `accepted_for_exact_task`'s exact logic
    // (sow.rs is not a library module -- this reimplements that pure, total check against the
    // REAL file the REAL binary wrote, rather than importing the private function; the logic is
    // reproduced verbatim from sow.rs's own `accepted_for_exact_task`).
    let state_lld = unique_dir("t13-lld-state");
    let out2 = run_sow_lld(&state_lld, &fixtures_dir().join("complete_freeze.json"));
    let stderr2 = stderr_of(&out2);
    assert_eq!(out2.status.code(), Some(9), "stderr:\n{stderr2}");
    let id2 = field(&stderr2, "SOW_READY_AWAITING_REVIEW ", "id").unwrap();
    let task_text2 = extract_delimited(&stderr2, "SOW_LLD_TASK_BEGIN", "SOW_LLD_TASK_END").unwrap();

    let accept_out = run_sow_accept(&state_lld, &id2);
    assert_eq!(
        accept_out.status.code(),
        Some(0),
        "stdout:\n{}\nstderr:\n{}",
        stdout_of(&accept_out),
        stderr_of(&accept_out)
    );

    let record2 = load_record(&state_lld, &id2);
    assert_eq!(record2["id"].as_str(), Some(id2.as_str()));
    assert_eq!(record2["task"].as_str(), Some(task_text2.as_str()));
    let accepted = &record2["accepted"];
    assert!(accepted["by"].is_string(), "accepted.by: {accepted}");
    assert!(accepted["at"].is_string(), "accepted.at: {accepted}");
    assert!(
        accepted["receipt"].is_string(),
        "accepted.receipt: {accepted}"
    );
    assert!(
        record2.get("lld_provenance").is_some(),
        "acceptance must not drop the provenance this lane attached: {record2}"
    );

    cleanup(&[&state_task, &state_lld]);
}

// ------------------------------------------------------------------------------------ T14 -----

#[test]
fn f07_t14a_pipe_in_failure_story_trigger_is_refused_not_silently_mangled() {
    let mut wrapper = load_fixture("complete_freeze");
    wrapper["module_brief"]["failure_story"]["trigger"] =
        json!("the trigger breaks | tradeoff: whatever happens next");
    rehash(&mut wrapper);
    assert!(
        lld::validate_lld_v1(&wrapper).is_empty(),
        "construction bug"
    );

    let path = write_temp_json("t14a-wrapper", "wrapper.json", &wrapper);
    let state = unique_dir("t14a-state");
    let out = run_sow_lld(&state, &path);
    let stdout = stdout_of(&out);
    assert_eq!(
        out.status.code(),
        Some(7),
        "stdout:\n{stdout}\nstderr:\n{}",
        stderr_of(&out)
    );
    assert_eq!(
        field(&stdout, "sow_lld_refused: ", "reason").as_deref(),
        Some("SOW_TEXT_PIPE_COLLISION")
    );
    assert!(sows_in(&state).is_empty());
    cleanup(&[&state]);
}

#[test]
fn f07_t14b_acceptance_marker_in_predicate_then_is_refused_not_silently_mangled() {
    let mut wrapper = load_fixture("complete_freeze");
    wrapper["sow_seed"]["blind_suite_seed"]["predicate"]["then"] =
        json!("lld-crosslang.sh reports acceptance: 3 mirrors agree");
    // sow_seed is not part of module_brief -- no rehash needed, content_hash is unaffected.
    assert!(
        lld::validate_lld_v1(&wrapper).is_empty(),
        "construction bug"
    );

    let path = write_temp_json("t14b-wrapper", "wrapper.json", &wrapper);
    let state = unique_dir("t14b-state");
    let out = run_sow_lld(&state, &path);
    let stdout = stdout_of(&out);
    assert_eq!(
        out.status.code(),
        Some(7),
        "stdout:\n{stdout}\nstderr:\n{}",
        stderr_of(&out)
    );
    assert_eq!(
        field(&stdout, "sow_lld_refused: ", "reason").as_deref(),
        Some("SOW_TEXT_MARKER_COLLISION")
    );
    assert!(sows_in(&state).is_empty());
    cleanup(&[&state]);
}
