//! F09: the contract suite for `fleet freeze stamp <brief.json> --out <lld.json>` (lane contract
//! `docs/lane-contracts/F09-orb-fleet-handoff.md` §7.1). Cargo INTEGRATION test -- drives the real
//! compiled `fleet` binary via subprocess for every CLI-observable property (exit codes, stdout/
//! stderr framing, on-disk ledger/`--out` side effects), and calls directly into `fleet::freeze` /
//! `fleet::lld_ready` for the two properties the CLI cannot reach (F09-T5's `MeasuredNothing`
//! branch) or that are cleaner to pin as a pure projection (F09-T10's exact literals).
//!
//! Per the lane contract's own instruction to this suite's builder: do not edit this file beyond
//! *adding* cases. Any diff that changes or removes an assertion below is a contract breach.
//! Fixtures needed beyond the read-only corpus (`fleet/contracts/fixtures/lld/**`, never edited)
//! are built in a tempdir at test runtime, matching `tests/f07_sow_intake.rs`'s own convention.

use fleet::freeze;
use fleet::lld;
use fleet::lld_ready::{self, GateRefs, Outcome};
use serde_json::{json, Value};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn fleet_bin() -> &'static str {
    env!("CARGO_BIN_EXE_fleet")
}

fn fixtures_dir() -> PathBuf {
    PathBuf::from(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/fixtures/lld"
    ))
}

fn load_fixture(name: &str) -> Value {
    let text = fs::read_to_string(fixtures_dir().join(format!("{name}.json")))
        .unwrap_or_else(|error| panic!("read fixture {name}: {error}"));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("parse fixture {name}: {error}"))
}

fn unique_dir(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "fleet-f09-{tag}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir_all(&dir).expect("create fixture dir");
    dir
}

fn write_temp_json(dir_tag: &str, file_name: &str, value: &Value) -> PathBuf {
    let dir = unique_dir(dir_tag);
    let path = dir.join(file_name);
    fs::write(
        &path,
        serde_json::to_vec_pretty(value).expect("serialize temp fixture"),
    )
    .expect("write temp fixture");
    path
}

fn refs() -> GateRefs {
    let owners_text = fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/owners.v1.json"
    ))
    .expect("read owners.v1.json");
    let owners_json: Value = serde_json::from_str(&owners_text).expect("parse owners.v1.json");
    let owners: Vec<String> = owners_json["owners"]
        .as_array()
        .expect("owners array")
        .iter()
        .map(|v| v.as_str().expect("owner is a string").to_string())
        .collect();

    let refs_text = fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../contracts/gate-refs.v1.json"
    ))
    .expect("read gate-refs.v1.json");
    let refs_json: Value = serde_json::from_str(&refs_text).expect("parse gate-refs.v1.json");
    let registry_paths: Vec<String> = refs_json["registry_paths"]
        .as_array()
        .expect("registry_paths array")
        .iter()
        .map(|v| v.as_str().expect("registry path is a string").to_string())
        .collect();
    let known_node_ids: Vec<String> = refs_json["known_node_ids"]
        .as_array()
        .expect("known_node_ids array")
        .iter()
        .map(|v| v.as_str().expect("known node id is a string").to_string())
        .collect();

    GateRefs {
        owners,
        registry_paths,
        known_node_ids,
    }
}

fn run_freeze_stamp(state: &Path, brief_path: &Path, out_path: &Path) -> Output {
    Command::new(fleet_bin())
        .arg("freeze")
        .arg("stamp")
        .arg(brief_path)
        .arg("--out")
        .arg(out_path)
        .env("FLEET_STATE", state)
        .output()
        .expect("run fleet freeze stamp")
}

fn run_gate_lld_ready(path: &Path) -> Output {
    Command::new(fleet_bin())
        .args(["gate", "lld-ready"])
        .arg(path)
        .output()
        .expect("run fleet gate lld-ready")
}

fn run_sow_lld(state: &Path, lld_path: &Path) -> Output {
    Command::new(fleet_bin())
        .arg("sow")
        .arg("--lld")
        .arg(lld_path)
        .env("FLEET_STATE", state)
        .output()
        .expect("run fleet sow --lld")
}

fn stdout_of(out: &Output) -> String {
    String::from_utf8_lossy(&out.stdout).into_owned()
}
fn stderr_of(out: &Output) -> String {
    String::from_utf8_lossy(&out.stderr).into_owned()
}

fn field(text: &str, prefix: &str, key: &str) -> Option<String> {
    text.lines()
        .find_map(|line| line.strip_prefix(prefix))?
        .split_whitespace()
        .find_map(|token| token.split_once('=').filter(|(k, _)| *k == key))
        .map(|(_, v)| v.to_string())
}

fn sows_in(state: &Path) -> Vec<PathBuf> {
    fs::read_dir(state.join("sows"))
        .map(|entries| {
            entries
                .filter_map(|entry| entry.ok())
                .map(|entry| entry.path())
                .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("json"))
                .collect()
        })
        .unwrap_or_default()
}

fn freezes_for(state: &Path, node_id: &str) -> Vec<PathBuf> {
    fs::read_dir(state.join("freezes").join(node_id))
        .map(|entries| {
            entries
                .filter_map(|entry| entry.ok())
                .map(|entry| entry.path())
                .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("json"))
                .collect()
        })
        .unwrap_or_default()
}

/// Any `.<name>.tmp-<pid>`-shaped residue anywhere directly under `dir` -- the atomic temp+rename
/// convention every on-disk write in this crate uses (`write_json_atomic`, `sow::write_atomic`).
fn tmp_residue_in(dir: &Path) -> Vec<PathBuf> {
    fs::read_dir(dir)
        .map(|entries| {
            entries
                .filter_map(|entry| entry.ok())
                .map(|entry| entry.path())
                .filter(|path| {
                    path.file_name()
                        .and_then(|name| name.to_str())
                        .is_some_and(|name| name.contains(".tmp-"))
                })
                .collect()
        })
        .unwrap_or_default()
}

fn cleanup(dirs: &[&Path]) {
    for dir in dirs {
        fs::remove_dir_all(dir).ok();
    }
}

// ------------------------------------------------------------------------------------- T1 -----

#[test]
fn f09_t1_happy_path_on_the_control_fixture() {
    let state = unique_dir("t1-state");
    let out_dir = unique_dir("t1-out");
    let out_path = out_dir.join("lld.json");
    let out = run_freeze_stamp(
        &state,
        &fixtures_dir().join("complete_module.json"),
        &out_path,
    );
    let stdout = stdout_of(&out);
    assert_eq!(out.status.code(), Some(0), "stderr:\n{}", stderr_of(&out));

    let freeze_id = field(&stdout, "FREEZE_STAMPED ", "freeze_id").expect("freeze_id field");
    assert!(
        freeze_id.starts_with("fz-") && freeze_id.len() == 19,
        "freeze_id shape: {freeze_id:?}"
    );
    assert!(
        freeze_id[3..]
            .bytes()
            .all(|b| b.is_ascii_hexdigit() && !b.is_ascii_uppercase()),
        "freeze_id must be fz-[0-9a-f]{{16}}: {freeze_id:?}"
    );
    assert_eq!(
        field(&stdout, "FREEZE_STAMPED ", "node_id").as_deref(),
        Some("lld-v1-schema")
    );
    assert_eq!(
        field(&stdout, "FREEZE_STAMPED ", "version").as_deref(),
        Some("1")
    );
    let content_hash =
        field(&stdout, "FREEZE_STAMPED ", "content_hash").expect("content_hash field");
    assert!(content_hash.starts_with("sha256:") && content_hash.len() == "sha256:".len() + 64);
    assert!(out_path.exists(), "--out file must exist");

    cleanup(&[&state, &out_dir]);
}

// ------------------------------------------------------------------------------------- T2 -----

#[test]
fn f09_t2_the_producer_consumer_contract_zero_violations_and_real_sow_intake_exit_9() {
    let state = unique_dir("t2-state");
    let out_dir = unique_dir("t2-out");
    let out_path = out_dir.join("lld.json");
    let stamp_out = run_freeze_stamp(
        &state,
        &fixtures_dir().join("complete_module.json"),
        &out_path,
    );
    assert_eq!(
        stamp_out.status.code(),
        Some(0),
        "stderr:\n{}",
        stderr_of(&stamp_out)
    );

    let wrapper: Value = serde_json::from_str(&fs::read_to_string(&out_path).expect("read --out"))
        .expect("parse --out as JSON");
    let violations = lld::validate_lld_v1(&wrapper);
    assert!(
        violations.is_empty(),
        "the producer's own output must validate against the merged consumer's validator: {violations:?}"
    );

    // The single most important test in this lane: the REAL compiled `fleet sow --lld` binary,
    // run against the file freeze stamp just wrote, with no fixture in between.
    let sow_out = run_sow_lld(&state, &out_path);
    assert_eq!(
        sow_out.status.code(),
        Some(9),
        "stdout:\n{}\nstderr:\n{}",
        stdout_of(&sow_out),
        stderr_of(&sow_out)
    );
    let records = sows_in(&state);
    assert_eq!(
        records.len(),
        1,
        "expected exactly one record under $FLEET_STATE/sows/"
    );

    cleanup(&[&state, &out_dir]);
}

// ------------------------------------------------------------------------------------- T3 -----

#[test]
fn f09_t3_keel_authored_the_stamp_not_the_input() {
    let state = unique_dir("t3-state");
    let out_dir = unique_dir("t3-out");
    let out_path = out_dir.join("lld.json");
    let brief_path = fixtures_dir().join("complete_module.json");
    let out = run_freeze_stamp(&state, &brief_path, &out_path);
    assert_eq!(out.status.code(), Some(0), "stderr:\n{}", stderr_of(&out));

    let wrapper: Value = serde_json::from_str(&fs::read_to_string(&out_path).expect("read --out"))
        .expect("parse --out");
    assert_eq!(
        wrapper["freeze"]["stamped_by"].as_str(),
        Some(lld_ready::STAMPED_BY)
    );

    // The INPUT brief's own raw bytes must contain zero occurrences of the stamp literal -- the
    // proposer's file never carried the string this lane's output now does.
    let brief_bytes = fs::read_to_string(&brief_path).expect("read input brief");
    assert_eq!(
        brief_bytes.matches(lld_ready::STAMPED_BY).count(),
        0,
        "the input brief must not itself contain the stamp literal"
    );

    cleanup(&[&state, &out_dir]);
}

// ------------------------------------------------------------------------------------- T4 -----

#[test]
fn f09_t4_exit_code_parity_with_gate_lld_ready_a_census_of_four_conditions() {
    let mut not_ready = load_fixture("complete_module");
    not_ready["open_questions"] = json!(["what store?"]);
    let not_ready_path = write_temp_json("t4-not-ready", "brief.json", &not_ready);

    let shape_invalid_path = fixtures_dir().join("one_line_freeze.json");

    let nonexistent_dir = unique_dir("t4-nonexistent");
    let nonexistent_path = nonexistent_dir.join("does-not-exist.json");

    let malformed_dir = unique_dir("t4-malformed");
    let malformed_path = malformed_dir.join("malformed.json");
    fs::write(&malformed_path, b"{not valid json").expect("write malformed fixture");

    let cases: [(&str, &Path); 4] = [
        ("NotReady", &not_ready_path),
        ("ShapeInvalid", &shape_invalid_path),
        ("NonexistentPath", &nonexistent_path),
        ("MalformedJson", &malformed_path),
    ];
    assert_eq!(
        cases.len(),
        4,
        "this is a census over exactly 4 shared conditions, not a sample"
    );

    for (label, path) in cases {
        let state = unique_dir(&format!("t4-state-{label}"));
        let out_dir = unique_dir(&format!("t4-out-{label}"));
        let out_path = out_dir.join("lld.json");

        let stamp_out = run_freeze_stamp(&state, path, &out_path);
        let gate_out = run_gate_lld_ready(path);
        assert_eq!(
            stamp_out.status.code(),
            gate_out.status.code(),
            "case {label}: freeze stamp exit {:?} must equal gate lld-ready exit {:?}",
            stamp_out.status.code(),
            gate_out.status.code()
        );
        assert!(
            !out_path.exists(),
            "case {label}: a refusal must never create the --out file"
        );
        cleanup(&[&state, &out_dir]);
    }
    cleanup(&[&nonexistent_dir, &malformed_dir]);
}

// ------------------------------------------------------------------------------------- T5 -----

#[test]
fn f09_t5_measured_nothing_never_stamps() {
    let brief = load_fixture("complete_module");
    let r = refs();

    // Not reachable through the CLI (which always calls `check_and_evaluate`, over the real
    // 14-check vocabulary) -- F06's own pub seam, used directly, exactly as the lane contract
    // names it.
    let verdict = lld_ready::evaluate_with(&brief, &r, &[]);
    assert_eq!(verdict.outcome, Outcome::MeasuredNothing);

    let projected = freeze::project_freeze(
        &brief,
        &verdict,
        "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "fz-0000000000000000",
        1,
        None,
    );
    assert!(
        projected.is_none(),
        "a MeasuredNothing verdict must never produce a freeze"
    );

    // Control: the SAME brief IS Ready under the real evaluator, and DOES project -- this is not
    // a bad fixture wearing a MeasuredNothing costume.
    let real_verdict = lld_ready::evaluate(&brief, &r);
    assert_eq!(real_verdict.outcome, Outcome::Ready);
    let projected_real = freeze::project_freeze(
        &brief,
        &real_verdict,
        "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "fz-0000000000000000",
        1,
        None,
    );
    assert!(projected_real.is_some());
}

// ------------------------------------------------------------------------------------- T6 -----

#[test]
fn f09_t6_version_and_supersedes() {
    let state = unique_dir("t6-state");
    let out_dir = unique_dir("t6-out");

    let brief_v1_path = fixtures_dir().join("complete_module.json");
    let out_v1 = out_dir.join("lld-v1.json");
    let stamp1 = run_freeze_stamp(&state, &brief_v1_path, &out_v1);
    assert_eq!(
        stamp1.status.code(),
        Some(0),
        "stderr:\n{}",
        stderr_of(&stamp1)
    );
    let stdout1 = stdout_of(&stamp1);
    assert_eq!(
        field(&stdout1, "FREEZE_STAMPED ", "version").as_deref(),
        Some("1")
    );
    let freeze_id_v1 = field(&stdout1, "FREEZE_STAMPED ", "freeze_id").expect("freeze_id v1");
    let wrapper1: Value = serde_json::from_str(&fs::read_to_string(&out_v1).unwrap()).unwrap();
    assert!(wrapper1["freeze"]["supersedes"].is_null());

    let mut mutated = load_fixture("complete_module");
    mutated["purpose"] = json!(format!(
        "{} (v2 edit)",
        mutated["purpose"].as_str().unwrap()
    ));
    let brief_v2_path = write_temp_json("t6-v2-brief", "brief.json", &mutated);
    let out_v2 = out_dir.join("lld-v2.json");
    let stamp2 = run_freeze_stamp(&state, &brief_v2_path, &out_v2);
    assert_eq!(
        stamp2.status.code(),
        Some(0),
        "stderr:\n{}",
        stderr_of(&stamp2)
    );
    let stdout2 = stdout_of(&stamp2);
    assert_eq!(
        field(&stdout2, "FREEZE_STAMPED ", "version").as_deref(),
        Some("2")
    );
    let wrapper2: Value = serde_json::from_str(&fs::read_to_string(&out_v2).unwrap()).unwrap();
    assert_eq!(
        wrapper2["freeze"]["supersedes"].as_str(),
        Some(freeze_id_v1.as_str())
    );

    let ledger_files = freezes_for(&state, "lld-v1-schema");
    let mut versions: Vec<String> = ledger_files
        .iter()
        .filter_map(|p| p.file_stem().and_then(|s| s.to_str()).map(str::to_string))
        .collect();
    versions.sort();
    assert_eq!(
        versions,
        vec!["1".to_string(), "2".to_string()],
        "both ledger entries must exist"
    );

    cleanup(&[&state, &out_dir]);
}

// ------------------------------------------------------------------------------------- T7 -----

#[test]
fn f09_t7_idempotency() {
    let state = unique_dir("t7-state");
    let out_dir = unique_dir("t7-out");
    let brief_path = fixtures_dir().join("complete_module.json");

    let out1 = out_dir.join("lld-1.json");
    let stamp1 = run_freeze_stamp(&state, &brief_path, &out1);
    assert_eq!(
        stamp1.status.code(),
        Some(0),
        "stderr:\n{}",
        stderr_of(&stamp1)
    );
    let stdout1 = stdout_of(&stamp1);
    let freeze_id_1 = field(&stdout1, "FREEZE_STAMPED ", "freeze_id").unwrap();
    let version_1 = field(&stdout1, "FREEZE_STAMPED ", "version").unwrap();

    let out2 = out_dir.join("lld-2.json");
    let stamp2 = run_freeze_stamp(&state, &brief_path, &out2);
    assert_eq!(
        stamp2.status.code(),
        Some(0),
        "stderr:\n{}",
        stderr_of(&stamp2)
    );
    let stdout2 = stdout_of(&stamp2);
    let freeze_id_2 = field(&stdout2, "FREEZE_STAMPED ", "freeze_id").unwrap();
    let version_2 = field(&stdout2, "FREEZE_STAMPED ", "version").unwrap();

    assert_eq!(
        freeze_id_1, freeze_id_2,
        "re-stamping an identical brief must yield the same freeze_id"
    );
    assert_eq!(
        version_1, version_2,
        "re-stamping an identical brief must yield the same version"
    );
    assert_eq!(version_1, "1");

    let ledger_files = freezes_for(&state, "lld-v1-schema");
    assert_eq!(
        ledger_files.len(),
        1,
        "an idempotent re-stamp must not append a second ledger entry"
    );

    cleanup(&[&state, &out_dir]);
}

// ------------------------------------------------------------------------------------- T8 -----

#[test]
fn f09_t8_nested_authority_key_graft_is_refused() {
    let mut brief = load_fixture("complete_module");
    // The exact slot F07 proved is never type/key-checked by `validate_module_brief` (only
    // kind/calc/enforced_by are ever read there) -- landmine #11.
    brief["guarantees"][0]["derivation"]["stamped_by"] = json!("attacker-supplied");
    let brief_path = write_temp_json("t8-brief", "brief.json", &brief);

    let state = unique_dir("t8-state");
    let out_dir = unique_dir("t8-out");
    let out_path = out_dir.join("lld.json");
    let out = run_freeze_stamp(&state, &brief_path, &out_path);
    let stdout = stdout_of(&out);
    assert_eq!(
        out.status.code(),
        Some(7),
        "stdout:\n{stdout}\nstderr:\n{}",
        stderr_of(&out)
    );
    assert_eq!(
        field(&stdout, "freeze_stamp_refused: ", "reason").as_deref(),
        Some("STAMP_KEY_PRESENT")
    );
    let path_field = field(&stdout, "freeze_stamp_refused: ", "path")
        .expect("path field naming the offending key");
    assert!(path_field.contains("stamped_by"), "{path_field}");
    assert!(
        !out_path.exists(),
        "a refusal must never create the --out file"
    );
    assert!(
        freezes_for(&state, "lld-v1-schema").is_empty(),
        "a refusal must never append a ledger entry"
    );

    cleanup(&[&state, &out_dir]);
}

// ------------------------------------------------------------------------------------- T9 -----

#[test]
fn f09_t9_numeric_leaf_graft_is_refused_as_unhashable() {
    let mut brief = load_fixture("complete_module");
    // A real JSON NUMBER (never a numeric-looking string) at the SAME unchecked slot T8 used, but
    // under a key name that is NOT one of the 6 forbidden keys -- so this reaches content_hash
    // (step 5), not the key scan (step 2) or shape (step 3), which is the whole point: a
    // top-level graft would be caught by shape first and would test the wrong layer.
    brief["guarantees"][0]["derivation"]["confidence"] = json!(0.87);
    let brief_path = write_temp_json("t9-brief", "brief.json", &brief);

    // Construction check: this must remain shape-valid AND gate-Ready, or this test exercises the
    // wrong layer (shape or the gate, not the hash guard).
    let r = refs();
    let verdict = lld_ready::evaluate(&brief, &r);
    assert_eq!(
        verdict.outcome,
        Outcome::Ready,
        "construction bug: mutation must remain gate-Ready"
    );
    assert!(
        lld::content_hash(&brief).is_err(),
        "construction bug: mutation must be unhashable"
    );

    let state = unique_dir("t9-state");
    let out_dir = unique_dir("t9-out");
    let out_path = out_dir.join("lld.json");
    let out = run_freeze_stamp(&state, &brief_path, &out_path);
    let stdout = stdout_of(&out);
    assert_eq!(
        out.status.code(),
        Some(7),
        "stdout:\n{stdout}\nstderr:\n{}",
        stderr_of(&out)
    );
    assert_eq!(
        field(&stdout, "freeze_stamp_refused: ", "reason").as_deref(),
        Some("FREEZE_UNHASHABLE")
    );
    assert!(!out_path.exists());
    assert!(freezes_for(&state, "lld-v1-schema").is_empty());

    cleanup(&[&state, &out_dir]);
}

// ---------------------------------------------------------------------------- M9 companion -----

#[test]
fn f09_m9_pin_a_claim_string_mentioning_the_keyword_is_accepted_not_refused() {
    // F05's exact recorded false positive, pinned here so a substring-grep regression (mutation
    // M9) cannot slip back in: a brief whose `guarantees[].claim` merely MENTIONS "stamped_by" in
    // prose (never as an object KEY) must be accepted, not refused.
    let mut brief = load_fixture("complete_module");
    let original_claim = brief["guarantees"][0]["claim"]
        .as_str()
        .unwrap()
        .to_string();
    brief["guarantees"][0]["claim"] = json!(format!(
        "{original_claim}; note that stamped_by only appears once this brief is gated"
    ));
    let brief_path = write_temp_json("m9-brief", "brief.json", &brief);

    let state = unique_dir("m9-state");
    let out_dir = unique_dir("m9-out");
    let out_path = out_dir.join("lld.json");
    let out = run_freeze_stamp(&state, &brief_path, &out_path);
    assert_eq!(
        out.status.code(),
        Some(0),
        "stdout:\n{}\nstderr:\n{}",
        stdout_of(&out),
        stderr_of(&out)
    );
    assert!(out_path.exists());

    cleanup(&[&state, &out_dir]);
}

// ------------------------------------------------------------------------------------ T10 -----

#[test]
fn f09_t10_the_projection_is_exact() {
    let brief = load_fixture("complete_module");
    let r = refs();
    let verdict = lld_ready::evaluate(&brief, &r);
    assert_eq!(verdict.outcome, Outcome::Ready);
    let content_hash = lld::content_hash(&brief).expect("control fixture must hash");
    let freeze_id = freeze::freeze_id_for(&content_hash, 1);

    let wrapper = freeze::project_freeze(&brief, &verdict, &content_hash, &freeze_id, 1, None)
        .expect("a Ready verdict must project");

    let freeze = &wrapper["freeze"];
    assert_eq!(freeze["schema_version"], json!("1.0"));
    assert_eq!(freeze["freeze_id"], json!(freeze_id));
    assert_eq!(freeze["version"], json!(1));
    assert_eq!(freeze["node_id"], json!("lld-v1-schema"));
    assert_eq!(freeze["content_hash"], json!(content_hash));
    assert_eq!(
        freeze["decision"],
        json!("Defines the frozen lld.v1 ModuleBrief/FreezeRecord shape and hand-mirrored TS+Python+Rust validators shared by downstream features.")
    );
    let expected_why = "Chosen over 2 killed alternatives: adopt ajv for JSON-Schema-backed runtime validation \u{2014} adds a runtime dependency no package.json here lists and no other Orb module uses yet; generate the Python/Rust validators from the JSON Schema at build time \u{2014} no codegen step exists in this repo's build; a hand-mirror plus the cross-language comparator is the smaller diff";
    assert_eq!(
        freeze["why"].as_str(),
        Some(expected_why),
        "got: {:?}",
        freeze["why"]
    );
    assert!(
        !expected_why.contains('|'),
        "construction check: the why formula itself must contain no pipe"
    );
    assert_eq!(freeze["killed_alternatives"], brief["alternatives"]);
    assert_eq!(
        freeze["accepts_when"],
        json!({
            "predicate": {
                "given": "a ModuleBrief fixture on disk",
                "when": "validateModuleBrief and validate_module_brief and validate_module_brief (rust) all parse it",
                "then": "apps/mobile/src/build/lld-v1.ts's validator agrees with the Python and Rust mirrors on the same verdict",
                "oracle_kind": "test"
            },
            "artifact": "apps/mobile/src/build/lld-v1.ts"
        })
    );
    assert_eq!(freeze["owner"], json!("rachit@devxlabs.ai"));
    assert_eq!(
        freeze["depth_evidence"],
        lld_ready::depth_evidence(&verdict).expect("Ready verdict carries evidence")
    );
    assert!(freeze["supersedes"].is_null());
    assert_eq!(freeze["stamped_by"], json!(lld_ready::STAMPED_BY));
    // Exactly the 13 fields of freeze.v1 -- an extra field here would also be a contract breach.
    assert_eq!(
        freeze.as_object().unwrap().len(),
        13,
        "freeze must carry exactly 13 fields: {freeze}"
    );

    let sow_seed = &wrapper["sow_seed"];
    let expected_restatement = "Build lld-v1-schema \u{2014} registry verdict build_new. Interface: validateModuleBrief, canonicalJson, contentHash. Fails if: the Python, TypeScript, and Rust validators drift after an edit lands in only one of them";
    assert_eq!(
        sow_seed["restatement"].as_str(),
        Some(expected_restatement),
        "got: {:?}",
        sow_seed["restatement"]
    );
    assert!(!expected_restatement.contains('|'));
    assert_eq!(
        sow_seed["blind_suite_seed"], freeze["accepts_when"],
        "must be byte-identical to freeze.accepts_when"
    );
    assert_eq!(
        sow_seed["blast_radius"],
        json!("the client accepts a brief the relay or fleet silently rejects, or vice versa, and a freeze attempt fails opaquely deep in the pipeline")
    );
    assert_eq!(sow_seed["owner"], json!("rachit@devxlabs.ai"));
    assert_eq!(sow_seed["registry_verdict"], brief["registry"]);
    assert_eq!(
        sow_seed.as_object().unwrap().len(),
        5,
        "sow_seed must carry exactly 5 fields: {sow_seed}"
    );

    // The projection must not merely look right in isolation: it must be what the merged
    // consumer's own validator accepts, with no fixture in between (echoes T2 at the library
    // level).
    assert!(lld::validate_lld_v1(&wrapper).is_empty());

    // Explicitly NOT an assertion that complete_freeze.json's hand-authored freeze is reproduced
    // (lane contract §3.3: that fixture predates any gate and its killed_alternatives are a
    // DIFFERENT list from its own brief's alternatives) -- recorded here so a future reader does
    // not "fix" this test to compare against that fixture.
    let hand_authored = load_fixture("complete_freeze");
    assert_ne!(
        freeze["killed_alternatives"], hand_authored["freeze"]["killed_alternatives"],
        "construction check: complete_freeze.json's hand-authored freeze really is a different \
         document from this projection -- if this ever passes, the fixture changed, not this test"
    );
}

// ------------------------------------------------------------------------------------ T11 -----

#[test]
fn f09_t11_fleet_state_unset() {
    let out_dir = unique_dir("t11-out");
    let out_path = out_dir.join("lld.json");
    let out = Command::new(fleet_bin())
        .arg("freeze")
        .arg("stamp")
        .arg(fixtures_dir().join("complete_module.json"))
        .arg("--out")
        .arg(&out_path)
        .env_remove("FLEET_STATE")
        .output()
        .expect("run fleet freeze stamp");
    assert_eq!(
        out.status.code(),
        Some(3),
        "stdout:\n{}\nstderr:\n{}",
        stdout_of(&out),
        stderr_of(&out)
    );
    let stderr = stderr_of(&out);
    assert!(
        stderr.contains("FLEET_STATE"),
        "the environment fault must be actionable, not silent: {stderr}"
    );
    assert!(!out_path.exists());

    cleanup(&[&out_dir]);
}

// ------------------------------------------------------------------------------------ T12 -----

#[test]
fn f09_t12_census_ratchet_on_the_forgery_literal() {
    const LITERAL: &str = "keel:lld-ready";
    let repo_root = PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../../.."));
    let rust_src = repo_root.join("fleet/keel/fleet/src");
    let python_src = repo_root.join("orb/backend/relay-py/src");

    let mut files_scanned = 0usize;
    let mut files_with_literal: Vec<String> = Vec::new();

    for (root, ext) in [(&rust_src, "rs"), (&python_src, "py")] {
        for entry in walk_files(root) {
            if entry.extension().and_then(|e| e.to_str()) != Some(ext) {
                continue;
            }
            files_scanned += 1;
            let text = fs::read_to_string(&entry).unwrap_or_default();
            if text.contains(LITERAL) {
                let relative = entry
                    .strip_prefix(&repo_root)
                    .unwrap_or(&entry)
                    .to_string_lossy()
                    .replace('\\', "/");
                files_with_literal.push(relative);
            }
        }
    }

    assert!(
        files_scanned > 0,
        "measuring nothing is a failure -- the walk found no source files"
    );

    files_with_literal.sort();
    files_with_literal.dedup();
    let mut allowed = vec![
        "fleet/keel/fleet/src/lld.rs".to_string(),
        "fleet/keel/fleet/src/lld_ready.rs".to_string(),
        "orb/backend/relay-py/src/orb_relay/proxy/lld_schemas.py".to_string(),
    ];
    allowed.sort();

    assert_eq!(
        files_with_literal, allowed,
        "the forgery literal must appear in EXACTLY the allowed validator-constant sites -- \
         equality, not `contains`. If this now includes handoff.py/app.py/freeze.rs, the orb or \
         the new keel command started constructing the string itself rather than referencing the \
         gate's own const."
    );
}

fn walk_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = fs::read_dir(dir) else {
        return out;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            out.extend(walk_files(&path));
        } else {
            out.push(path);
        }
    }
    out
}

// ------------------------------------------------------------------------------------ T13 -----

#[test]
fn f09_t13_no_partial_artifacts_on_any_refusal_path_and_no_tmp_residue_on_success() {
    // Refusal path (STAMP_KEY_PRESENT, same construction as T8): no --out, no ledger, no tmp
    // residue anywhere near the attempted output.
    let mut bad_brief = load_fixture("complete_module");
    bad_brief["guarantees"][0]["derivation"]["stamped_by"] = json!("attacker-supplied");
    let bad_brief_path = write_temp_json("t13-bad-brief", "brief.json", &bad_brief);

    let state = unique_dir("t13-state");
    let out_dir = unique_dir("t13-out");
    let out_path = out_dir.join("lld.json");
    let refused = run_freeze_stamp(&state, &bad_brief_path, &out_path);
    assert_eq!(refused.status.code(), Some(7));
    assert!(!out_path.exists());
    assert!(
        tmp_residue_in(&out_dir).is_empty(),
        "a refusal must leave no tmp residue in the out dir"
    );
    assert!(freezes_for(&state, "lld-v1-schema").is_empty());

    // Success path (same state dir, so a stray leftover from the refusal above would also show
    // up here): --out exists, and no `.tmp-*` file is left behind anywhere.
    let out2_path = out_dir.join("lld2.json");
    let ok = run_freeze_stamp(
        &state,
        &fixtures_dir().join("complete_module.json"),
        &out2_path,
    );
    assert_eq!(ok.status.code(), Some(0), "stderr:\n{}", stderr_of(&ok));
    assert!(out2_path.exists());
    assert!(
        tmp_residue_in(&out_dir).is_empty(),
        "a successful stamp must leave no tmp residue in the out dir"
    );
    let ledger_dir = state.join("freezes").join("lld-v1-schema");
    assert!(
        tmp_residue_in(&ledger_dir).is_empty(),
        "a successful stamp must leave no tmp residue in the ledger dir"
    );

    cleanup(&[&state, &out_dir]);
}
